# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbd984251c8d9ec9a31b50175ea6a6cac348a331b8cf0036d4cfab6734b4e71962e461d7753a574a138d9770d8baf719bb1013c5ca6c0d9ad0dc5a15726b4f58

test:
  secret_key_base: 97984751c2e5f456401638fb8d98da70fc1918726c1ac1f1164a93b49fbd7ee4127da0bd7eb66a94063001e41e5e1fda189bff71dcf1590c41e84e6edcec9e60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
